# Make list of optical H_2 lines

For comparison with our Deep Red Lines

In [1]:
from pathlib import Path
import numpy as np
import pandas as pd
import seaborn as sns
from astropy import units as u
from specutils.utils.wcs_utils import vac_to_air, air_to_vac
from astropy.table import QTable

In [45]:
cloudy_path = Path.home() / "Work/PNe/Peter/herschel-helix-models/models/static/"
save_path = Path.cwd().parent.parent / "data-atomic"

Read in the molecular hydrogen line list.  This is a Helix Nebula model from an abandoned project from 2013. Eventually, I should replace it with a better model for NGC 346

In [39]:
df = pd.read_csv(cloudy_path / "static_n20big.h2l", sep="\t")

Take the second half of the file

In [40]:
df = df.loc[618:]

Select all lines with wavelengths less than 0.93 micron

In [41]:
ddf = df.query("`wl(mic)` < 0.93").sort_values("wl(mic)")
ddf

,#H2 line,Ehi,Vhi,Jhi,Elo,Vlo,Jlo,wl(mic),wl(lab),log L or I,I/Inorm,"Excit(hi, K)",g_u h nu * Aul
1068,6-1 S(9),0,6,11,0,1,9,0.568919,5689A,29.763,0.000175,38099.677,1.365000e-17
1153,6-1 S(12),0,6,14,0,1,12,0.590453,5905A,29.573,0.000113,41671.153,5.954000e-18
1147,7-2 S(9),0,7,11,0,2,9,0.613353,6134A,29.880,0.000229,41557.792,3.130000e-17
916,4-0 S(9),0,4,11,0,0,9,0.626962,6270A,29.527,0.000102,30138.752,8.314000e-18
1180,8-3 S(7),0,8,9,0,3,7,0.652961,6530A,29.552,0.000107,42884.301,3.981000e-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...
873,5-2 S(1),0,5,3,0,2,1,0.922920,9229A,29.649,0.000134,27374.185,1.161000e-17
1240,13-7 O(2),0,13,0,0,7,2,0.923122,9231A,29.524,0.000101,50862.722,3.049000e-19
1169,9-5 S(0),0,9,2,0,5,0,0.923291,9233A,29.947,0.000267,42184.610,2.374000e-18
1224,9-5 S(8),0,9,10,0,5,8,0.926411,9264A,30.035,0.000326,46520.724,3.715000e-17
775,4-1 O(2),0,4,0,0,1,2,0.929753,9298A,30.295,0.000594,21941.939,2.755000e-19

In [43]:
ddf = ddf.assign(
    wav_air=vac_to_air(ddf['wl(mic)'].to_numpy() * u.micron).to(u.Angstrom).value,
)

In [44]:
ddf

,#H2 line,Ehi,Vhi,Jhi,Elo,Vlo,Jlo,wl(mic),wl(lab),log L or I,I/Inorm,"Excit(hi, K)",g_u h nu * Aul,wav_air
1068,6-1 S(9),0,6,11,0,1,9,0.568919,5689A,29.763,0.000175,38099.677,1.365000e-17,5687.523819
1153,6-1 S(12),0,6,14,0,1,12,0.590453,5905A,29.573,0.000113,41671.153,5.954000e-18,5902.803023
1147,7-2 S(9),0,7,11,0,2,9,0.613353,6134A,29.880,0.000229,41557.792,3.130000e-17,6131.740278
916,4-0 S(9),0,4,11,0,0,9,0.626962,6270A,29.527,0.000102,30138.752,8.314000e-18,6267.794761
1180,8-3 S(7),0,8,9,0,3,7,0.652961,6530A,29.552,0.000107,42884.301,3.981000e-17,6527.707103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
873,5-2 S(1),0,5,3,0,2,1,0.922920,9229A,29.649,0.000134,27374.185,1.161000e-17,9226.530490
1240,13-7 O(2),0,13,0,0,7,2,0.923122,9231A,29.524,0.000101,50862.722,3.049000e-19,9228.549913
1169,9-5 S(0),0,9,2,0,5,0,0.923291,9233A,29.947,0.000267,42184.610,2.374000e-18,9230.238431
1224,9-5 S(8),0,9,10,0,5,8,0.926411,9264A,30.035,0.000326,46520.724,3.715000e-17,9261.431520
775,4-1 O(2),0,4,0,0,1,2,0.929753,9298A,30.295,0.000594,21941.939,2.755000e-19,9294.842976

In [46]:
ddf.to_csv(save_path / "cloudy-h2-lines.csv")